ENABLE_DEBUG_LOGS = false
ENABLE_TRIAL_POTION_RECIPE = true
BLACKLISTED_STRUCTURE_IDS = []
REPLACE_GENERATED_SPAWNERS_WITH_COBBLEMON_SPAWNERS = true
REPLACE_SPAWNERS_IN_STRUCTURES_WITH_COBBLEMON_SPAWNERS = true
REPLACE_ANY_UNSPECIFIED_SPAWNERS_WITH_DEFAULT_COBBLEMON_SPAWNERS = true
REPLACE_ANY_BLOCKS_WITH_COBBLEMON_SPAWNERS = true
SPAWNED_POKEMON_ARE_UNCATCHABLE = true
SPAWNED_POKEMON_MUST_BE_DEFEATED_IN_BATTLE = true
ALLOW_SPAWNED_POKEMON_TO_BE_AGGRESSIVE = true
MOB_SPAWNER_REPLACEMENT_PERCENTAGE = 1.0
TRIAL_SPAWNER_REPLACEMENT_PERCENTAGE = 1.0
BLOCK_REPLACEMENT_PERCENTAGE = 1.0
ALPHA_POKEMON_PERCENTAGE = 0.1
ENABLE_POKEMON_LEVEL_ADJUSTMENT = true
POKEMON_LEVEL_ADJUSTMENT_TYPE = "AVERAGE"
TIME_TILL_POKEMON_DESPAWN_IN_TICKS = 6000
