#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Tue Aug 18 00:58:40 PYT 2026
alwaysLogTamperWarnings=true
