name = "Cobblemon Adventure"
author = "Cobbleverse Team"
version = "1.0.0"
description = "Cobblemon 1.21.1 Fabric Modpack Single Source of Truth"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98bf854c9bb6c4af4eb7a3abb873587999858bd749c0c760de1431f5b9266859"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
